name: Build and Publish NuGet Packages

on:
  push:
    branches: [main, develop]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  DOTNET_VERSION_8: "8.0.x"
  DOTNET_VERSION_9: "9.0.x"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION_8 }}
            ${{ env.DOTNET_VERSION_9 }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Display Version
        run: |
          echo "Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          echo "Semantic Version: ${{ steps.gitversion.outputs.semVer }}"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }} /p:ContinuousIntegrationBuild=true

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Pack NuGet packages
        run: |
          dotnet pack src/MarkdownToRazor/MarkdownToRazor.csproj --configuration Release --no-build --output ./packages /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} /p:ContinuousIntegrationBuild=true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./packages/*.nupkg

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: ./coverage/**/*.xml

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ./packages

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION_8 }}
            ${{ env.DOTNET_VERSION_9 }}

      - name: Publish to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          for pkg in ./packages/*.nupkg; do
            echo "Publishing $pkg to NuGet.org"
            dotnet nuget push "$pkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
          done

      - name: Create GitHub Release (for tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          body: |
            ## Changes in this Release

            See the [CHANGELOG.md](CHANGELOG.md) for details.

            ## NuGet Package

            The following package has been published to **NuGet.org**:

            ### 📦 **Install from NuGet.org:**
            ```bash
            dotnet add package MarkdownToRazor
            ```

            ## Package Description

            - **`MarkdownToRazor`** - Complete solution for converting Markdown files to Blazor Razor pages with runtime components, build-time code generation, and MSBuild integration

            ## Installation & Usage

            See [README.md](README.md) for complete installation and usage instructions.
